[package]
name = "b"
version = "0.1.0"
authors = ["Michael Mattig <mattig@mathematik.uni-marburg.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
